spring:
  application:
    name: transfers-core
  r2dbc:
    url: r2dbc:h2:mem:///transfersdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.bancoias.transfers: DEBUG
